// Generates the app's secrets and writes them to apps/web/.env.local (gitignored).
// Usage: node scripts/generate-secrets.mjs "your-login-password"
import { randomBytes, scryptSync } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const password = process.argv[2];
if (!password) {
  console.error('Usage: node scripts/generate-secrets.mjs "your-login-password"');
  process.exit(1);
}

const salt = randomBytes(16);
const hash = scryptSync(password, salt, 64);
const authPasswordHash = `scrypt:${salt.toString("hex")}:${hash.toString("hex")}`;

const authSecret = randomBytes(32).toString("base64");
const fieldEncryptionKey = randomBytes(32).toString("base64");

const lines = [
  "# Generated by scripts/generate-secrets.mjs — DO NOT COMMIT.",
  "# Paste these into Vercel > Project > Settings > Environment Variables.",
  "",
  "# --- Fill this one in yourself from the Supabase dashboard ---",
  "# Project Settings > Database > Connection string > Transaction pooler",
  'DATABASE_URL=""',
  "",
  "# --- Generated below ---",
  `AUTH_SECRET="${authSecret}"`,
  `AUTH_PASSWORD_HASH="${authPasswordHash}"`,
  "",
  "# CRITICAL: back this key up somewhere safe. It encrypts your PAN/Aadhaar/bank",
  "# details at rest. If you lose it, that data is unrecoverable; if you change it,",
  "# previously-saved data can no longer be decrypted.",
  `FIELD_ENCRYPTION_KEY="${fieldEncryptionKey}"`,
  "",
  "# Set your login email here (the only account that can sign in)",
  'AUTH_USER_EMAIL=""',
  "",
  "# Optional until you enable Form 16 uploads (Vercel > Storage > Blob)",
  'BLOB_READ_WRITE_TOKEN=""',
  "",
];

const outPath = join(process.cwd(), "apps", "web", ".env.local");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote secrets to ${outPath}`);
console.log("Open that file to copy the values into Vercel. It is gitignored.");
